const UserList = [
  {
    id: 1,
    name: 'john',
    username: 'john',
    age: 20,
    nationality: 'AMERICAN',
    friends: [
      {
        id: 2,
        name: 'pedro',
        username: 'pedrotech',
        age: 20,
        nationality: 'BRAZILIAN',
      },
    ],
  },
  {
    id: 2,
    name: 'pedro',
    username: 'pedrotech',
    age: 20,
    nationality: 'BRAZILIAN',
    friends: [
      {
        id: 1,
        name: 'john',
        username: 'john',
        age: 20,
        nationality: 'AMERICAN',
      },
    ],
  },
  {
    id: 3,
    name: 'mike',
    username: 'mike',
    age: 20,
    nationality: 'GERMAN',
    friends: [
      {
        id: 1,
        name: 'john',
        username: 'john',
        age: 20,
        nationality: 'AMERICAN',
      },
      {
        id: 4,
        name: 'vince',
        username: 'vince',
        age: 20,
        nationality: 'SPANISH',
      },
      {
        id: 8,
        name: 'lala',
        username: 'lala',
        age: 20,
        nationality: 'PAKISTANI',
      },
      {
        id: 10,
        name: 'mischief',
        username: 'mischief',
        age: 20,
        nationality: 'GERMAN',
      },
    ],
  },
  {
    id: 4,
    name: 'vince',
    username: 'vince',
    age: 20,
    nationality: 'SPANISH',
    friends: [
      {
        id: 1,
        name: 'john',
        username: 'john',
        age: 20,
        nationality: 'AMERICAN',
      },
      {
        id: 3,
        name: 'mike',
        username: 'mike',
        age: 20,
        nationality: 'GERMAN',
      },
      {
        id: 8,
        name: 'lala',
        username: 'lala',
        age: 20,
        nationality: 'PAKISTANI',
      },
      {
        id: 10,
        name: 'mischief',
        username: 'mischief',
        age: 20,
        nationality: 'GERMAN',
      },
    ],
  },
  {
    id: 5,
    name: 'mark',
    username: 'mark',
    age: 20,
    nationality: 'FRENCH',
    friends: [
      {
        id: 6,
        name: 'danny',
        username: 'danny',
        age: 20,
        nationality: 'CANADIAN',
      },
    ],
  },
  {
    id: 6,
    name: 'danny',
    username: 'danny',
    age: 20,
    nationality: 'CANADIAN',
    friends: [
      {
        id: 5,
        name: 'mark',
        username: 'mark',
        age: 20,
        nationality: 'FRENCH',
      },
    ],
  },
  {
    id: 7,
    name: 'jordan',
    username: 'jordan',
    age: 20,
    nationality: 'ITALIAN',
  },
  {
    id: 8,
    name: 'lala',
    username: 'lala',
    age: 20,
    nationality: 'PAKISTANI',
    friends: [
      {
        id: 1,
        name: 'john',
        username: 'john',
        age: 20,
        nationality: 'AMERICAN',
      },
      {
        id: 4,
        name: 'vince',
        username: 'vince',
        age: 20,
        nationality: 'SPANISH',
      },
      {
        id: 3,
        name: 'mike',
        username: 'mike',
        age: 20,
        nationality: 'GERMAN',
      },
      {
        id: 10,
        name: 'mischief',
        username: 'mischief',
        age: 20,
        nationality: 'GERMAN',
      },
    ],
  },
  {
    id: 9,
    name: 'james',
    username: 'james',
    age: 20,
    nationality: 'FINNISH',
    friends: [
      {
        id: 1,
        name: 'john',
        username: 'john',
        age: 20,
        nationality: 'AMERICAN',
      },
      {
        id: 4,
        name: 'vince',
        username: 'vince',
        age: 20,
        nationality: 'SPANISH',
      },
      {
        id: 8,
        name: 'lala',
        username: 'lala',
        age: 20,
        nationality: 'PAKISTANI',
      },
      {
        id: 10,
        name: 'mischief',
        username: 'mischief',
        age: 20,
        nationality: 'GERMAN',
      },
    ],
  },
  {
    id: 10,
    name: 'mischief',
    username: 'mischief',
    age: 20,
    nationality: 'GERMAN',
    friends: [
      {
        id: 1,
        name: 'john',
        username: 'john',
        age: 20,
        nationality: 'AMERICAN',
      },
      {
        id: 4,
        name: 'vince',
        username: 'vince',
        age: 20,
        nationality: 'SPANISH',
      },
      {
        id: 8,
        name: 'lala',
        username: 'lala',
        age: 20,
        nationality: 'PAKISTANI',
      },
      {
        id: 3,
        name: 'mike',
        username: 'mike',
        age: 20,
        nationality: 'GERMAN',
      },
    ],
  },
];

const MovieList = [
  {
    id: 1,
    name: 'The Avengers',
    yearPublished: 2012,
    inTheaters: true,
  },
  {
    id: 2,
    name: 'Avengers: Age of Ultron',
    yearPublished: 2015,
    inTheaters: true,
  },
  {
    id: 3,
    name: 'Avengers: Infinity War',
    yearPublished: 2018,
    inTheaters: true,
  },
  {
    id: 4,
    name: 'Avengers Endgame',
    yearPublished: 2019,
    inTheaters: true,
  },
  {
    id: 5,
    name: 'John Wick',
    yearPublished: 2014,
    inTheaters: true,
  },
  {
    id: 6,
    name: 'John Wick: Chapter 2',
    yearPublished: 2017,
    inTheaters: true,
  },
  {
    id: 7,
    name: 'John Wick: Chapter 3',
    yearPublished: 2019,
    inTheaters: true,
  },
  {
    id: 8,
    name: 'John Wick: Chapter 4',
    yearPublished: 2023,
    inTheaters: true,
  },
  {
    id: 9,
    name: 'Random1',
    yearPublished: 2020,
    inTheaters: false,
  },
  {
    id: 10,
    name: 'Random2',
    yearPublished: 2025,
    inTheaters: false,
  },
];

module.exports = { UserList, MovieList };
